import type { Metadata } from "next";
import RegisterPage from "./page";

export const metadata: Metadata = {
  title: "Login page",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <RegisterPage />
      </body>
    </html>
  )
}
